/**
 * @fileoverview Defines the IUser interface for user data.
 * @version 1.0.0
 * @module userInterface
 */

import { Optional } from 'sequelize';
import { UserRoleType } from '../types';

/**
 * Interface representing the attributes of a user.
 */
interface IUser {
  id?: number;
  avatar_uri?: string;
  email?: string;
  phone?: string;
  password?: string;
  role?: UserRoleType;
  verified?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

interface IUserQuery {
  id?: number;
  email?: string;
}

interface IUpdateContactQuery {
  email?: string;
  phone?: string;
}

interface IUpdatePasswordQuery {
  currentPassword?: string;
  new_password?: string;
  confirm_password?: string;
}

/**
 * Interface for creating a new user (excluding autogenerated fields).
 */
type IUserCreation = Optional<IUser, 'id' | 'createdAt' | 'updatedAt'>;

export {
  IUser,
  IUserQuery,
  IUpdateContactQuery,
  IUpdatePasswordQuery,
  IUserCreation,
};
